### ISSUE TITLE
Output fails if path contains spaces

### ISSUE THREAD

**Issue by Smileyrasmus** [seaty6/jumpcutterV2#6]
https://github.com/seaty6/jumpcutterV3GUI/blob/10f260262b8c88b009bfa8c4cd2ebf1058de7d4a/JumpCutterGUI_AIO.py#L307

Fix by replacing line 307 with following line:
command = 'ffmpeg -y -i spedup.mp4 -i spedupAudio.wav -c:v copy -c:a aac "{}"'.format(outFile)

**Comment by seaty6** [comment]
Thank you! I've added your fix.
